default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV.fetch("PGUSER") { ENV.fetch("USER") } %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>

development:
  <<: *default
  database: honeywagon_development

test:
  <<: *default
  database: honeywagon_test

production:
  primary:
    <<: *default
    database: honeywagon_production
  cache:
    <<: *default
    database: honeywagon_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: honeywagon_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: honeywagon_production_cable
    migrations_paths: db/cable_migrate

services:
  postgres:
    image: postgres:16
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: honeywagon_test
    ports:
      - 5432:5432
    options: >-
      --health-cmd "pg_isready -U postgres"
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5